# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Qrpk7mDOZ5go4sb41PDMV9cPce9ChM-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pprint
# %matplotlib inline

df = pd.read_csv("/content/pro.csv")

print("First 5 rows \n ")
print(df.head())
print()

print("Dataset information \n")
print(df.info())
print()

print("Dataset description \n")
print(df.describe())
print()

df.loc[~df.index.duplicated(), :]

print("Not null Values \n")
print(df.isnull().sum())
print()

#DF to Month Year Date and Time
df1 = df
df1["Month"] = pd.to_datetime(df["Datetime"]).dt.month
df1["Year"] = pd.to_datetime(df["Datetime"]).dt.year
df1["Date"] = pd.to_datetime(df["Datetime"]).dt.date
df1["Time"] = pd.to_datetime(df["Datetime"]).dt.time
df1["Day"] = pd.to_datetime(df["Datetime"]).dt.day_name()
df1 = df.set_index("Datetime")
df1.index = pd.to_datetime(df1.index)
print(df1.head())

# unique Years
print("Unique Years: \n")
print(df1.Year.unique(),"\n")
print("Unique Years : ",df1.Year.nunique())

from matplotlib import style

fig = plt.figure()

ax1= fig.add_subplot(311)
ax2= fig.add_subplot(312)
ax3= fig.add_subplot(313)

plt.title("Energy consumptionnin")
style.use('ggplot')

y_2004 = df1[df1["Year"] == 2004]["AEP_MW"].to_list()
x_2004 = df1[df1["Year"] == 2004]["Date"].to_list()
ax1.plot(x_2004,y_2004, color="blue", linewidth=1.7)


y_2005 = df1[df1["Year"] == 2005]["AEP_MW"].to_list()
x_2005 = df1[df1["Year"] == 2005]["Date"].to_list()
ax2.plot(x_2005, y_2005, color="green", linewidth=1)


y_2006 = df1[df1["Year"] == 2006]["AEP_MW"].to_list()
x_2006 = df1[df1["Year"] == 2006]["Date"].to_list()
ax3.plot(x_2006, y_2006, color="red", linewidth=1)


plt.rcParams["figure.figsize"] = (18,8)

plt.xlabel("Date")
plt.ylabel("Energy in MW")
plt.grid(True, alpha=1)
plt.legend()
plt.title("Energy consumption")
plt.show()

##Energy Distrinution
sns.displot(df1["AEP_MW"],color = 'r')
plt.title("Energy Distribution")
plt.show()


##Energy with respect to Time
fig = plt.figure()
ax1= fig.add_subplot(111)

sns.lineplot(x=df["Month"],y=df["AEP_MW"], data=df)
plt.title("Energy Consumption vs Month ")
plt.xlabel("Time")
plt.grid(True, alpha=1)
plt.legend()
plt.show()

##Resampling Data

# df1['Date'] = pd.to_datetime(df1['Date'])  # Convert 'Date' column to datetime
# df1.set_index('Date', inplace=True)
# NewDataset = df1.resample('D').mean()
# print("old dataset",df1.shape)
# print("new dataset",NewDataset.shape)

# print(NewDataset.head())
# df1 = df1.apply(pd.to_numeric, errors='coerce')
NewDataset = df1.resample('D')[df1.select_dtypes(include='number').columns].mean()
# print(NewDataset.head())

TestData = NewDataset.tail(100)

Training_Set = NewDataset.iloc[:,0:1]
Training_Set = Training_Set[:-60]

# print("Training Set Shape ", Training_Set.shape)
# print("Test Set Shape ", TestData.shape)

from sklearn.preprocessing import MinMaxScaler
#Training_Set = Training_Set.values
sc = MinMaxScaler(feature_range = (0,1))
Train = sc.fit_transform(Training_Set)
# print(Train)


X_Train = []
Y_Train = []

# Range should be fromm 60 Values to END
for i in range(60, Train.shape[0]):

    # X_Train 0-59
    X_Train.append(Train[i-60:i])

    # Y Would be 60 th Value based on past 60 Values
    Y_Train.append(Train[i])

# Convert into Numpy Array
X_Train = np.array(X_Train)
Y_Train = np.array(Y_Train)

# print(X_Train.shape)
# print(Y_Train.shape)

X_Train = np.reshape(X_Train, newshape=(X_Train.shape[0], X_Train.shape[1], 1))
# print(X_Train.shape)

#MODEL BUILDING:

from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential
regressor = Sequential()

# # Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_Train.shape[1], 1)))
regressor.add(Dropout(0.2))

# # Adding a second LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# # Adding a third LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

# # Adding a fourth LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

# # Adding the output layer
regressor.add(Dense(units = 1))

# # Compiling the RNN
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

regressor.fit(X_Train, Y_Train, epochs = 100, batch_size = 32)

# Select only the AEP_MW column to match the features used during training
inputs = NewDataset[-(60 + 100):][['AEP_MW']]
inputs_scaled = sc.transform(inputs)

X_test = []

for i in range(60, inputs_scaled.shape[0]):
    X_test.append(inputs_scaled[i-60:i])

X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

# Predicting the energy consumption
predicted_energy = regressor.predict(X_test)

# Inverse transform to get actual values
predicted_energy = sc.inverse_transform(predicted_energy)

# Actual values for comparison
real_energy = TestData["AEP_MW"].values

# Evaluation
from sklearn.metrics import mean_squared_error, mean_absolute_error
import math

rmse = math.sqrt(mean_squared_error(real_energy, predicted_energy))
mae = mean_absolute_error(real_energy, predicted_energy)

print("Root Mean Squared Error (RMSE):", rmse)
print("Mean Absolute Error (MAE):", mae)

# Plotting results
plt.figure(figsize=(15, 6))
plt.plot(real_energy, color='blue', label='Actual Energy Consumption')
plt.plot(predicted_energy, color='red', label='Predicted Energy Consumption')
plt.title('Energy Forecast vs Actual (Last 100 Days)')
plt.xlabel('Time')
plt.ylabel('AEP in MW')
plt.legend()
plt.grid(True)
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
import math

##LINEAR REGRESSION
# Create lag features for linear regression (e.g., previous 1 day)
Train_LR = Training_Set.copy()
Train_LR['Prev'] = Train_LR['AEP_MW'].shift(1)
Train_LR = Train_LR.dropna()

X_lr = Train_LR[['Prev']].values
y_lr = Train_LR['AEP_MW'].values

model_lr = LinearRegression()
model_lr.fit(X_lr, y_lr)

# For prediction, we use the last value from training as initial input
preds_lr = []
last_value = Training_Set['AEP_MW'].iloc[-1]

for i in range(100):
    pred = model_lr.predict([[last_value]])[0]
    preds_lr.append(pred)
    last_value = pred

rmse_lr = math.sqrt(mean_squared_error(TestData["AEP_MW"], preds_lr))
mae_lr = mean_absolute_error(TestData["AEP_MW"], preds_lr)

#RANDOM FOREST REGRESSOR
# Similar lag feature approach
Train_RF = Training_Set.copy()
Train_RF['Prev'] = Train_RF['AEP_MW'].shift(1)
Train_RF = Train_RF.dropna()

X_rf = Train_RF[['Prev']].values
y_rf = Train_RF['AEP_MW'].values

model_rf = RandomForestRegressor(n_estimators=100, random_state=0)
model_rf.fit(X_rf, y_rf)

# Predict 100 future values iteratively
preds_rf = []
last_value = Training_Set['AEP_MW'].iloc[-1]

for i in range(100):
    pred = model_rf.predict([[last_value]])[0]
    preds_rf.append(pred)
    last_value = pred

rmse_rf = math.sqrt(mean_squared_error(TestData["AEP_MW"], preds_rf))
mae_rf = mean_absolute_error(TestData["AEP_MW"], preds_rf)

#ARIMA
# Fit ARIMA on entire training set
model_arima = ARIMA(Training_Set['AEP_MW'], order=(5,1,0))
model_arima_fit = model_arima.fit()

forecast_arima = model_arima_fit.forecast(steps=100)

rmse_arima = math.sqrt(mean_squared_error(TestData["AEP_MW"], forecast_arima))
mae_arima = mean_absolute_error(TestData["AEP_MW"], forecast_arima)

print("Model Performance Comparison:\n")
print(f"LSTM        -> RMSE: {rmse:.2f}, MAE: {mae:.2f}")
print(f"LinearReg   -> RMSE: {rmse_lr:.2f}, MAE: {mae_lr:.2f}")
print(f"RandomForest-> RMSE: {rmse_rf:.2f}, MAE: {mae_rf:.2f}")
print(f"ARIMA       -> RMSE: {rmse_arima:.2f}, MAE: {mae_arima:.2f}")

plt.figure(figsize=(14,6))

# Plot only the last 100 points with appropriate indexing
plt.plot(range(100), TestData["AEP_MW"].values, label="Actual", color='orangered', linewidth=2)
plt.plot(range(100), predicted_energy, label="LSTM", linestyle='--', color='royalblue')
plt.plot(range(100), preds_lr, label="Linear Regression", color='mediumorchid')
plt.plot(range(100), preds_rf, label="Random Forest", color='gray')
plt.plot(range(100), forecast_arima, label="ARIMA", color='gold')

plt.title("Forecast Comparison (Last 100 Days)", fontsize=16)
plt.xlabel("Days", fontsize=12)
plt.ylabel("AEP in MW", fontsize=12)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

#ERROR DISTRIBUTION COMPARISON
errors = {
    "LSTM": TestData["AEP_MW"].values - predicted_energy,
    "Linear Regression": TestData["AEP_MW"].values - preds_lr,
    "Random Forest": TestData["AEP_MW"].values - preds_rf,
    "ARIMA": TestData["AEP_MW"].values - forecast_arima,
}

plt.figure(figsize=(14,6))
for model, error in errors.items():
    plt.hist(error, bins=20, alpha=0.6, label=model)

plt.title("Forecast Error Distribution", fontsize=16)
plt.xlabel("Error (Actual - Predicted)", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

import numpy as np

models = ['LSTM', 'Linear Regression', 'Random Forest', 'ARIMA']
rmses = [rmse, rmse_lr, rmse_rf, rmse_arima]
maes = [mae, mae_lr, mae_rf, mae_arima]

x = np.arange(len(models))
width = 0.35

plt.figure(figsize=(12,6))
plt.bar(x - width/2, rmses, width, label='RMSE', color='cornflowerblue')
plt.bar(x + width/2, maes, width, label='MAE', color='lightcoral')

plt.ylabel('Error', fontsize=12)
plt.title('Model Performance Comparison', fontsize=16)
plt.xticks(x, models)
plt.legend()
plt.grid(axis='y')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Ensure all predictions are 1D arrays
predicted_energy_1d = np.ravel(predicted_energy)
preds_lr_1d = np.ravel(preds_lr)
preds_rf_1d = np.ravel(preds_rf)
forecast_arima_1d = np.ravel(forecast_arima)

# Create residuals DataFrame
residuals_df = pd.DataFrame({
    "LSTM": TestData["AEP_MW"].values - predicted_energy_1d,
    "Linear Regression": TestData["AEP_MW"].values - preds_lr_1d,
    "Random Forest": TestData["AEP_MW"].values - preds_rf_1d,
    "ARIMA": TestData["AEP_MW"].values - forecast_arima_1d,
}, index=TestData.index)

# Plotting
plt.figure(figsize=(14, 6))

for col in residuals_df.columns:
    plt.plot(residuals_df.index, residuals_df[col], label=col, linewidth=1.5)

plt.title("Model Residuals Over Time", fontsize=16)
plt.xlabel("Time", fontsize=12)
plt.ylabel("Residual (Actual - Predicted)", fontsize=12)
plt.legend(title="Model", loc="upper right")
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()